function trials = get_trial_names()
    trials = {{{"Normal level walking"}, {"Slow level walking"}, {"Fast level walking"}, ... 
        {"Jogging"}, {"Walking backwards"}, {"Turning on the spot (CW)"}, ...
        {"Turning on the spot (CCW)"}, {"Side stepping (L)"}, {"Side stepping (R)"}...
        {"Circular walking (diam 2m)(CW)"}, {"Circular walking (diam 2m)(CCW)"}}; ... % Recording 1
        ...
        {{'Stair ascent (SOS)(L first)(1)'}, {'Stair descent (SOS)(L first)(1)'}, ...
        {'Stair ascent (SOS)(R first)(1)'}, {'Stair descent (SOS)(R first)(1)'}, ...
        {'Stair ascent (SBS)(L first)(1)'}, {'Stair descent (SBS)(L first)(1)'}, ...
        {'Stair ascent (SBS)(R first)(1)'}, {'Stair descent (SBS)(R first)(1)'}, ...
        {'Stair ascent (SOS)(L first)(2)'}, {'Stair descent (SOS)(L first)(2)'}, ...
        {'Stair ascent (SOS)(R first)(2)'}, {'Stair descent (SOS)(R first)(2)'}, ...
        {'Stair ascent (SBS)(L first)(2)'}, {'Stair descent (SBS)(L first)(2)'}, ...
        {'Stair ascent (SBS)(R first)(2)'}, {'Stair descent (SBS)(R first)(2)'}, ...
        {'Stair ascent (SOS)(L first)(3)'}, {'Stair descent (SOS)(L first)(3)'}, ...
        {'Stair ascent (SOS)(R first)(3)'}, {'Stair descent (SOS)(R first)(3)'}, ...
        {'Stair ascent (SBS)(L first)(3)'}, {'Stair descent (SBS)(L first)(3)'}, ...
        {'Stair ascent (SBS)(R first)(3)'}, {'Stair descent (SBS)(R first)(3)'}, ...
        {'Stair ascent (SOS)(L first)(4)'}, {'Stair descent (SOS)(L first)(4)'}, ...
        {'Stair ascent (SOS)(R first)(4)'}, {'Stair descent (SOS)(R first)(4)'}, ...
        {'Stair ascent (SBS)(L first)(4)'}, {'Stair descent (SBS)(L first)(4)'}, ...
        {'Stair ascent (SBS)(R first)(4)'}, {'Stair descent (SBS)(R first)(4)'}, ...
        {'Stair ascent (SOS)(L first)(5)'}, {'Stair descent (SOS)(L first)(5)'}, ...
        {'Stair ascent (SOS)(R first)(5)'}, {'Stair descent (SOS)(R first)(5)'}, ...
        {'Stair ascent (SBS)(L first)(5)'}, {'Stair descent (SBS)(L first)(5)'}, ...
        {'Stair ascent (SBS)(R first)(5)'}, {'Stair descent (SBS)(R first)(5)'}, ...
        ... % {'Stair ascent (SOS)(L first)(6)'}, {'Stair descent (SOS)(L first)(6)'}, ...
        ... % {'Stair ascent (SOS)(R first)(6)'}, {'Stair descent (SOS)(R first)(6)'}, ...
        ... % {'Stair ascent (SBS)(L first)(6)'}, {'Stair descent (SBS)(L first)(6)'}, ...
        ... % {'Stair ascent (SBS)(R first)(6)'}, {'Stair descent (SBS)(R first)(6)'}, ... % add for subject 15 session 1
        {'Ramp ascent (10deg)'}, {'Ramp descent (10deg)'}, ...
        {'Standing'}, {'Squat'}, {'Calf raises'}, ...
        {'Sitting'}, {'Sit-to-stand and stand-to-sit'}, ...
        {'Free knee flexion-extension'}, {'Free ankle flexion-extension'}}; % Recording 2
        ...
        {{"Normal level walking weight"}, {"Slow level walking weight"}, ...
        {"Fast level walking weight"}, {"Jogging weight"}, {"Walking backwards weight"}, ... walk BW bakpack not done by subj11
        {"Turning on the spot (CW) weight"}, {"Turning on the spot (CCW) weight"}, ...
        {"Side stepping (L) weight"}, {"Side stepping (R) weight"}, ... % not executed by subject 4
        {"Circular walking (diam 2m)(CW) weight"}, {"Circular walking (diam 2m)(CCW) weight"}, ...
        {"Normal level walking obstacle"}, {"Slow level walking obstacle"}, ...
        {"Fast level walking obstacle"}, {"Walking backwards obstacle"}, ... % add for subj1 session4: {"Jogging obstacle"}
        {"Side stepping (L) obstacle"}, {"Side stepping (R) obstacle"}...
        {"Circular walking (diam 2m)(CW) obstacle"}, {"Circular walking (diam 2m)(CCW) obstacle"}}; ... % Recording 3
        ...
        {{'Stair ascent (SOS)(L first) weight'}, {'Stair descent (SOS)(L first) weight'}, ...
        {'Stair ascent (SOS)(R first) weight'}, {'Stair descent (SOS)(R first) weight'}, ...
        {'Stair ascent (SBS)(L first) weight'}, {'Stair descent (SBS)(L first) weight'}, ...
        {'Stair ascent (SBS)(R first) weight'}, {'Stair descent (SBS)(R first) weight'}, ...
        {'Ramp ascent (10deg) weight'}, {'Ramp descent (10deg) weight'}, ...
        {'Standing weight'}, {'Squat weight'}, {'Calf raises weight'}, ...
        {'Sit-to-stand and stand-to-sit weight'}, ... % Not done by subject 2 and 3
        {'Stair ascent (SOS)(L first) obstacle'}, {'Stair descent (SOS)(L first) obstacle'}, ...
        {'Stair ascent (SOS)(R first) obstacle'}, {'Stair descent (SOS)(R first) obstacle'}, ...
        {'Stair ascent (SBS)(L first) obstacle'}, {'Stair descent (SBS)(L first) obstacle'}, ...
        {'Stair ascent (SBS)(R first) obstacle'}, {'Stair descent (SBS)(R first) obstacle'}, ...
        {'Ramp ascent (10deg) obstacle'}, {'Ramp descent (10deg) obstacle'}, ...
        {'Standing obstacle'}, {'Squat obstacle'}, {'Calf raises obstacle'}, ...
        {'Sitting obstacle'}, {'Sit-to-stand and stand-to-sit obstacle'}}; %... % Recording 4 % last 2 not done by subj1
        ...
        {{"Sit-to-stand-to-walk"}, {"Combination 1"}, ...
        {"Combination 2"}, {"Combination 3"}}}; ... % Recording 5
end

% {'Stair ascent (SBS)(R first)(6)'}, {'Stair descent (SBS)(R first)(6)'}, ... % add this row for subject1 session2